### ISSUE TITLE
establish exact behaviour of dat

### ISSUE THREAD

**Issue by jtauber** [jtauber/dcpu16py#17]
it's not clear to me whether

`dat "Hello"`

is supposed to generate 5 words or 3 (with one byte of padding)

Any ideas?

**Comment by andre-d** [comment]
Double quotes for words, if you want padded half words use single quotes (No example from Notch has done this, I just like the idea).  In this cpu a "byte" is a 16bit word.  That is my understanding of it.

**Comment by andre-d** [comment]
Ie. Half words are secondary

**Comment by jtauber** [comment]
So you're saying "Hello" would be 3 16bit words? So string manipulation is two characters at a time?

**Comment by andre-d** [comment]
No, "Hello" would be five 16bit words.  I am suggesting an extension whereby 'Hello' is 3 16bit words.

**Comment by jtauber** [comment]
Ah got it. Then it appears the contributed `asm_pyparsing` has a bug.

**Comment by andre-d** [comment]
I would only say so because of some graphics code I saw of notches in a screenshot somewhere which seemed to assume the upper half of every byte would be 0x00, and otherwise the background color was being set.

SEEMED TO BE! Not positive on that, but given that on this arch all bytes are words, I doubt itd be dealing with half bytes like that

**Comment by jtauber** [comment]
I agreed with you, was just wanting to check because I was confused by the asm_pyparsing behaviour and wanted to get confirmation that at least someone else thought it was a bug.

**Comment by jtauber** [comment]
I've implemented DAT with the 16-bit per character interpretation in 49bc7e15104bad4aeb10cbeb86eb10697a8af1e7
