### ISSUE TITLE
Replace magic numbers throughout the code with constants

### ISSUE THREAD

**Issue by andre-d** [jtauber/dcpu16py#19]
Most of the magic hex values can be moved into a common constants file with names.  Makes for cleaner, more understandable, code.

**Comment by jtauber** [comment]
Not sure I agree. But which ones did you have in mind? Having a magic number for 0x0 or 0x10000 doesn't seem worth it and almost all the rest are just the op codes or addressing modes.

I have thought about simplifying things by putting SP, PC and O at 0x1B 0x1C and 0x1D respectively in `self.registers[]` rather than at 8, 9 and 10 like they currently are. Then they wouldn't need to be special-cased so much in `get_operand`

**Comment by andre-d** [comment]
if l < 0x20:
                b = 0x20 + l
            else:
                b = 0x1F
                y = l

For an example, is not clear what any of those hex values actually are

**Comment by jtauber** [comment]
I'm not sure giving them a label (rather than, say, a comment) would actually make it that much clearer, tbh. Better commenting might be the way to go.

**Comment by andre-d** [comment]
Well, consider what happens if you ever need to change one of the values.

**Comment by jtauber** [comment]
that would be a pretty big instruction set change for one of those numbers to change and would probably require more than just a couple of magic numbers to update. seems overengineering to plan for such changes, especially when we're talking about < 200 lines of code.
