### ISSUE TITLE
Single line program fails to run

### ISSUE THREAD

**Issue by shauncarpenter** [jtauber/dcpu16py#60]
The program

```
SET A, 100
```

Fails to emulate with the error:

```
  File "/usr/local/bin/dcpu16", line 289, in <module>
    dcpu16.run(trace=args.trace, show_speed=args.speed)
  File "/usr/local/bin/dcpu16", line 215, in run
    op = self.opcodes[opcode]
KeyError: 0
```

It's almost as if the emulator is going over the end of the binary.

**Comment by andre-d** [comment]
0x100 or 0x64, decimal is not yet supported, and usually indicated by a 'd' at the end.  Like 100d

**Comment by shauncarpenter** [comment]
There must be something strange about my environment (Archlinux), because even without the literal

```
SET A, B
```

I still get the same error.

**Comment by swarmer** [comment]
It doesn't fail, processor just goes to the next memory location. 
There isn't any code there and garbage instead (well, actually, zeros), so processor fails.
If you try to assemble similar code for x86 it will segfault too, and you'll have to make explicit system call to stop the process.
So the only problem is that error message could be more explicit.

That's why you can see infinite loop at the end of all examples. I don't know of `halt` instruction for DCPU, so the only thing you can do is to hang it forever.

**Comment by andre-d** [comment]
Oh, right xD thought he was assembling

**Comment by shauncarpenter** [comment]
Ah, I see.  Sorry for the seemingly useless issue then.
Thanks!

**Comment by jtauber** [comment]
@andre-d fwiw, decimal is supported and it assembles just fine

**Comment by jtauber** [comment]
@swarmer I agree it should crash exactly like that; it should probably just be a no-op if the opcode is unknown
