### ISSUE TITLE
implement the video

### ISSUE THREAD

**Issue by ojii** [jtauber/dcpu16py#9]
http://i.imgur.com/XIXc4.jpg

Not sure how this would work in python, maybe just print to stdout?

**Comment by jtauber** [comment]
in ApplePy I used PyGame so I'll likely implement video in dcpu16py the same way

**Comment by jtauber** [comment]
working on this on video branch now

**Comment by enkore** [comment]
Keyboard input seems to either work via memory mapping at 0x9000 or the dat instructions. I can't really read the DCPU16 asm (yet): http://pastebin.com/raw.php?i=aJSkRMyC

**Comment by andre-d** [comment]
PyGame has no python3 support, I will also work on a QT video branch.  If we do it via a plugin-like (give them a reference to the cpu or memory then thread them off) system we could have them side-by-side.

**Comment by enkore** [comment]
Sounds like a good idea in my opinion.
I would propose the following architecture:
- Directory "renderer" contains one file for each renderer
- A renderer should be a class handling video output and keyboard input (as they often go together, don't they?)
- The interface should be probably not too low-level
- I would propose to have a updateVideo() function or something similar taking the contents of the "VRAM" as a string or StringIO
- Keyboard input could be handled either via polling or callback, so that the renderer calls a function of the CPU (I would personally prefer that, because its more efficient)
- Command line parameter (probably something like -r or --render) is the python path to the class in the module (in the renderer directory)

**Comment by andre-d** [comment]
Why not just make them totally different modules?  I don't see any reason for video/input logic to be in the cpu core.

**Comment by andre-d** [comment]
The VRAM is not exactly a concept the CPU knows about.  I would say to just pass it a reference at start and thread it off calling it good.  Let the video handle it's own world and just read cpu.memory

**Comment by enkore** [comment]
Would be probably better, but then we should provide a mechanism to register callbacks when a (specific) memory region changes, because polling is just... dirty and inefficient. That would probably be a very clean solution.
Those callbacks could be registered via a decorator, like this:
`
@watch_memory(0x8000, 0x8FFF)
vram_changed(memory):`

I could implement that, but of course this decision is jtaubers'

**Comment by andre-d** [comment]
I have implemented the plugin portion in #30, if you want to watch for memory changes you could import a decorator like that within the plugin.

**Comment by enkore** [comment]
Uhm the plugins run not in sync with the CPU, the ticks of the plugins are not equal to the cycles of the CPU. This can lead to inconsistent behaviour/states, but I don't know how or if Python protects against those.
Anyway it would be cleaner/more efficient if all plugins get called once per CPU cycle...

**Comment by andre-d** [comment]
Why would they run in sync with the CPU.   In real life the clock of PCI is not the CPU clock.....Either way, we can put a lock on the cpu and unlock it once per clock....if we want to make sure they get syncd.  No need to call them though.  I do not like the idea of running them in sync with the CPU though, as you might want a display which is a lot faster than the 100khz cpu.

**Comment by enkore** [comment]
Although that is correct, the PCI clock is synced with the CPU clock. If it wasn't reads and writes would randomly fail ;)

To optimize perfomance (or the analogy towards a real computer) a plugin class could contain a property `divider` that determines how often the tick is called.

**Comment by andre-d** [comment]
Why not just stick a lock inside the cpu which we lock during any instruction? Then plugins can acquire that lock too in order to ensure no plugins conflict with eachother.

**Comment by enkore** [comment]
Locks are evil. Cost perfomance and so on. Really synced solution is better...

**Comment by andre-d** [comment]
It would not be that much cost to performance as there will always be a LOT of host cpu time between ticks.

**Comment by andre-d** [comment]
jtauber might have to speak up on the "locking vs call once per tick" issue

**Comment by enkore** [comment]
It's his decision anyway ;)

Am 06.04.2012 18:45, schrieb Andre d:

**Comment by jtauber** [comment]
I'm going to start off just putting a PyGame solution inline (like I did with ApplePy). Obviously this makes it unrunnable on Python3 or PyPy. This was actually why, in ApplePy, we switched to two processes.

I'm not suggesting doing it exactly the same way as ApplePy but it's worth taking a look at it as one approach.

**Comment by jtauber** [comment]
Actually, I might make an [IN PROGRESS] pull request on my video branch and move the conversation there.
